name: Static Checks
on:
  push:
    branches-ignore:
      - gh-pages
      - l10n_master
  pull_request:
    paths:
      - "addons/**"
      - "src/**"
      - ".github/workflows/static-checks.yml"

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-static
  cancel-in-progress: true

jobs:
  static-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - name: Install GDScript toolkit
        run: |
          python -m pip install --upgrade setuptools
          python -m pip install "gdtoolkit==4.*"
      - name: Formatting checks
        run: gdformat --diff .
      - name: Linting checks
        run: gdlint .
      - name: Spell checks via codespell
        uses: codespell-project/actions-codespell@v2
        with:
          skip: ./addons,./Translations,./installer,./src/UI/Dialogs/AboutDialog.gd,./src/Classes/SoftwareParsers/PhotoshopParser.gd
          ignore_words_list: chello,doubleclick,Manuel,SectionIn
